name: CI/CD for Dockerized Flaskk App

on:
  push:
    branches: [ main ]
  pull_request :
    branches: [ main ]
   
jobs:
  build-and-test:
    run-on: ubuntu-latest


    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      used: actions/setup-python@v4
      with:
        python-version: '3.9'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask 
        pip install pytest

    - name: Run test
      run: |
        pytest
    
    build-and-publish:
      needs : build-and-test
      runs on: ubuntu-latest